# Generated by Django 5.0.6 on 2024-07-01 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landr', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Master',
            new_name='masters',
        ),
    ]
