# Generated by Django 5.0.6 on 2024-07-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landr', '0004_remove_iptable_id_alter_iptable_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='iptable',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='iptable',
            name='ip_address',
            field=models.CharField(max_length=32),
        ),
    ]
