# Generated by Django 5.0.6 on 2024-07-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landr', '0005_iptable_id_alter_iptable_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iptable',
            name='id',
        ),
        migrations.AlterField(
            model_name='iptable',
            name='ip_address',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
